# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PDDQgisPlugin
                                 A QGIS plugin
 Descarga de datos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-10
        copyright            : (C) 2022 by Sebastián Castro
        email                : sebastian.castro@itrend.cl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PDDQgisPlugin class from file PDDQgisPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pdd_qgis_plugin import PDDQgisPlugin
    return PDDQgisPlugin(iface)
